#!/bin/bash

MESSAGE="Updated via git-updategit"

border() {
    title="| $1 |"
    edge=$(echo "$title" | sed 's/./-/g')
    echo "$edge"
    echo "$title"
    echo "$edge"
}

update () {
    border ${PWD##*/}
    printf %"$(tput cols)"s |tr " " "-"
    git add .
    git commit -m "$1"
    git push
    printf %"$(tput cols)"s |tr " " "-"
}

if [ $# == 0 ]
then  
    if [ -e .git ] 
    then
        update $MESSAGE
    fi
else
    for i in $@ 
    do
        if [ -d $i ] 
        then
            cd $i
            if [ -e .git ] 
            then
                update $MESSAGE
            fi
            cd ..
        fi
    done
fi