#!/bin/bash

MESSAGE="git-update"

border() {
    title="| $@ |"
    edge=$(echo "$title" | sed 's/./-/g')
    echo "$edge"
    echo "$title"
    echo "$edge"
}

update () {
    border ${PWD##*/}
    printf %"$(tput cols)"s |tr " " "-"
    if [ -e .git ]
    then
        git add .
        git commit -m " $@ "
        git push
    else
        echo "No .git file exists"
    fi
    printf %"$(tput cols)"s |tr " " "-"
}

if [ $# == 0 ]
then  
    update "$MESSAGE"
else
    for i in $@ 
    do
        if [ -d $i ] 
        then
            cd $i
            update "$MESSAGE"
            cd ..
        fi
    done
fi